/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeledriveSandboxRouteImport } from './routes/teledrive-sandbox'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeledriveSandboxRoute = TeledriveSandboxRouteImport.update({
  id: '/teledrive-sandbox',
  path: '/teledrive-sandbox',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/teledrive-sandbox': typeof TeledriveSandboxRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/teledrive-sandbox': typeof TeledriveSandboxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/teledrive-sandbox': typeof TeledriveSandboxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/teledrive-sandbox'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/teledrive-sandbox'
  id: '__root__' | '/' | '/teledrive-sandbox'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TeledriveSandboxRoute: typeof TeledriveSandboxRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teledrive-sandbox': {
      id: '/teledrive-sandbox'
      path: '/teledrive-sandbox'
      fullPath: '/teledrive-sandbox'
      preLoaderRoute: typeof TeledriveSandboxRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TeledriveSandboxRoute: TeledriveSandboxRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
